spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank Cards related local APIs"
  contactDetails:
    name: "Card bae - Developer"
    email: "Card@eazybank.com"
  onCallSupports:
    - (555) 555-1234
    - (555) 555-1345
