server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - application_qa.yml
      - application_prod.yml

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank Cards related local APIs"
  contactDetails:
    name: "Card bae - Developer"
    email: "Card@eazybank.com"
  onCallSupports:
    - (555) 555-1234
    - (555) 555-1345
