#Start with a base image containing Java runtime
FROM eclipse-temurin:21-jdk-alpine-3.21

# Information around who maintains the image
LABEL "org.opencontainers.image.authors"="pavlo.v"

# Add the application's jar to the image
COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

# Execute the application
ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]
