server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - application_qa.yml
      - application_prod.yml

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Loan local bae - Developer"
    email: "loan@eazybank.com"
  onCallSupports:
    - (555) 555-1234
    - (555) 555-1345

