spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "loan sang - Developer"
    email: "loan@eazybank.com"
  onCallSupports:
    - (555) 555-1234
    - (555) 555-1345
