build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs - Unique"
  contactDetails:
    name: "Jane Doe - Cards"
    email: "jane.cards@eazybank.com"
  onCallSupports:
    - (555) 222-2222
    - (555) 222-2223
