build:
  version: "2.0-qa"

cards:
  message: "Welcome to EazyBank cards related QA APIs - Unique"
  contactDetails:
    name: "Jane Doe - QA Cards"
    email: "jane.qa.cards@eazybank.com"
  onCallSupports:
    - (555) 222-3332
    - (555) 222-3333
