build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs - Unique"
  contactDetails:
    name: "Peter Jones - Loans"
    email: "peter.loans@eazybank.com"
  onCallSupports:
    - (555) 333-3333
    - (555) 333-3334
