build:
  version: "2.0-qa"

loans:
  message: "Welcome to EazyBank loans related QA APIs - Unique"
  contactDetails:
    name: "Peter Jones - QA Loans"
    email: "peter.qa.loans@eazybank.com"
  onCallSupports:
    - (555) 333-4443
    - (555) 333-4444
