spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Jake bae - Developer"
    email: "jake@eazybank.com"
  onCallSupports:
    - (555) 555-1234
    - (555) 555-1345
